//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelComplexWPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailedInformationAboutThePerson
    {
        public int ID { get; set; }
        public int HumanID { get; set; }
        public string Patronymic { get; set; }
        public int GenderID { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int PassportSeries { get; set; }
        public int PassportNumber { get; set; }
        public string PassportFile { get; set; }
        public Nullable<int> CityAddressID { get; set; }
        public string ResidenceAddress { get; set; }
        public string SNILS { get; set; }
        public string INN { get; set; }
    
        public virtual City City { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Human Human { get; set; }
    }
}
