//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelComplexWPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.User = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public int DetailedInformationAboutThePersonID { get; set; }
        public int RoleID { get; set; }
        public int EducationID { get; set; }
        public int HotelID { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public decimal SalaryAmount { get; set; }
    
        public virtual DetailedInformationAboutThePerson DetailedInformationAboutThePerson { get; set; }
        public virtual Education Education { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual EmployeePosition EmployeePosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
