//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelComplexWPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelRoom()
        {
            this.ReservationHotelRoom = new HashSet<ReservationHotelRoom>();
        }
    
        public int ID { get; set; }
        public int HotelID { get; set; }
        public int CategoryID { get; set; }
        public int TypeID { get; set; }
        public int FloorHR { get; set; }
        public int NumberOfRoomsHR { get; set; }
        public decimal PriceHR { get; set; }
        public int StatusID { get; set; }
        public string DescriptionNotes { get; set; }
    
        public virtual CategoryHotelRoom CategoryHotelRoom { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual StatusHotelRoom StatusHotelRoom { get; set; }
        public virtual TypeHotelRoom TypeHotelRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationHotelRoom> ReservationHotelRoom { get; set; }
    }
}
