//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelComplexWPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationHotelRoom
    {
        public int ID { get; set; }
        public int HotelRoomID { get; set; }
        public int ClientID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string DescriptionNotes { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual HotelRoom HotelRoom { get; set; }
    }
}
